set -g status on
set -g status-bg "#1F1F28"
set -g status-fg "#DCD7BA"

# Active window
set -g window-status-current-style "bg=#2A2A37,fg=#C8C093"

# Inactive windows
set -g window-status-style "bg=#1F1F28,fg=#727169"

